"""
LLM-as-Judge Post-hoc evaluation of chosen clarification question
Should be run after run_baselines.py produced results/baselines.jsonl

RQ1: RQ1: Does an ambiguity-aware clarification strategy produce more relevant clarification questions than an ambiguity-agnostic strategy?
Clarification Question Quality (CQQ) (score of 1-5 on each)
- Faithfulness - no hallucinated content
- Reasonableness - targets the gap in the user's intent
- Clarity - specific and easy for a user to answer
- ReferenceSimilarity - semantic closeness to the gold clarification (BERTScore proxy)

RQ2: Does it lead to higher answer accuracy once clarification is resolved? 
- VQA Score - not implemented yet, we could add a second Gemini call to predict if the generated clarification would lead to a correct answer (or predict the VQA score based on the generated clarification and gold intended question)

For Gemini prompting we use the PTCF framework (Persona, Task, Context, Format) to maximize consistency of the judge's scores.
"""

import argparse
import json
import os
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Optional
from google import genai
from google.genai import types as genai_types
from tqdm import tqdm

sys.path.insert(0, str(Path(__file__).resolve().parent))

DEFAULT_INPUT = os.path.join("results", "baselines.jsonl")
DEFAULT_OUTPUT = os.path.join("results", "judge_scores.jsonl")
JUDGE_MODEL = "gemini-2.0-flash"
MAX_RETRIES = 4
RETRY_DELAY = 4

JUDGE_SYSTEM = """\
### Persona
You are an NLP researcher evaluating clarification questions generated by a VLM \
for intent-underspecified visual questions. Intent underspecification means the \
visual target is clear but the user's intended aspect is not \
e.g. "Tell me about this building" could mean architecture, history, or function.
 
### Task
Score the generated clarification question on four 1-5 dimensions. Do not explain your scores. \
 
### Context
Inputs you will receive:
- Ambiguous question: the original user question
- Generated clarification: the VLM's clarification question
- Model reasoning: the VLM's reasoning if present (CoT conditions only)
- Gold clarification: human-written reference from ClearVQA
 
Dimensions:
Faithfulness — grounded in the question, no invented details
PASS: "Are you asking about its architecture or history?"
FAIL: "Is it the red car or blue car?" (colors not mentioned)
5 = fully grounded  3 = minor unsupported assumption  1 = hallucinated content
 
Reasonableness — targets a genuine intent gap, not something already clear
PASS: asks which aspect of the scene the user cares about
FAIL: asks something trivially obvious or already stated
5 = precisely targets missing intent  3 = plausible but not the key gap  1 = irrelevant
 
Clarity — specific and answerable in a few words, asks one thing
Avoid: vague openers like "Can you clarify?" or multi-part questions
5 = clear and directly answerable  3 = mildly vague  1 = confusing 
 
ReferenceSimilarity — semantic closeness to the gold clarification
5 = same intent, different wording  3 = same topic, misses specifics  1 = unrelated
 
### Format
Return ONLY these four lines, no preamble, no markdown:
Faithfulness: <1-5>
Reasonableness: <1-5>
Clarity: <1-5>
ReferenceSimilarity: <1-5>
"""

SCORE_KEYS = ["Faithfulness", "Reasonableness", "Clarity", "ReferenceSimilarity"]

def call_judge(client: genai.Client, ambiguous_question: str,
               generated_clarification: str, gold_clarification: str,
               reasoning: Optional[str] = None) -> dict:
    reasoning_block = f"\nModel reasoning: {reasoning}" if reasoning else ""
    user_msg = (
        f"Ambiguous question: {ambiguous_question}\n"
        f"Generated clarification: {generated_clarification}"
        f"{reasoning_block}\n"
        f"Gold reference clarification: {gold_clarification}"
    )

    for attempt in range(MAX_RETRIES):
        try:
            response = client.models.generate_content(
                model=JUDGE_MODEL,
                contents=user_msg,
                config=genai_types.GenerateContentConfig(
                    system_instruction=JUDGE_SYSTEM,
                    max_output_tokens=128,
                    temperature=0.0,
                ),
            )
            return _parse(response.text.strip())
        except Exception as e:
            if "429" in str(e) or "quota" in str(e).lower() or "rate" in str(e).lower():
                if attempt < MAX_RETRIES - 1:
                    time.sleep(RETRY_DELAY * (attempt + 1))
                    continue
            return {"judge_error": str(e)}
    return {"judge_error": "max retries exceeded"}


def _parse(text: str) -> dict:
    scores: dict = {}
    for key in SCORE_KEYS:
        scores[key.lower()] = None
        for line in text.splitlines():
            if key.lower() in line.lower() and ":" in line:
                try:
                    scores[key.lower()] = float(line.split(":")[-1].strip().split()[0])
                    break
                except (ValueError, IndexError):
                    pass

    cqq_vals = [scores[k] for k in ("faithfulness", "reasonableness", "clarity") if scores[k] is not None]
    scores["cqq_mean"] = round(sum(cqq_vals) / len(cqq_vals), 3) if cqq_vals else None
    scores["_raw"] = text
    return scores


def load_results(path: str) -> list[dict]:
    results = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    results.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return results


def load_completed(path: str) -> set[tuple]:
    completed = set()
    if not os.path.exists(path):
        return completed
    for r in load_results(path):
        try:
            completed.add((r["id"], r["condition"]))
        except KeyError:
            pass
    return completed

def print_summary(path: str):
    records = load_results(path)
    if not records:
        return

    agg: dict = defaultdict(lambda: defaultdict(list))
    for r in records:
        cond = r.get("condition", "unknown")
        for k in ["faithfulness", "reasonableness", "clarity", "referencesimilarity", "cqq_mean"]:
            if r.get(k) is not None:
                agg[cond][k].append(r[k])

    keys = ["faithfulness", "reasonableness", "clarity", "referencesimilarity", "cqq_mean"]
    print(f"{'condition':<14}" + "".join(f"{k:<22}" for k in keys))
    for cond in sorted(agg):
        row = f"{cond:<14}"
        for k in keys:
            vals = agg[cond][k]
            row += f"{sum(vals)/len(vals):<22.3f}" if vals else f"{'N/A':<22}"
        print(row)
    print()

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input",  default=DEFAULT_INPUT)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument("--limit",  type=int, default=None,
                        help="Max examples per condition (for testing)")
    parser.add_argument("--resume", action="store_true",
                        help="Skip already-evaluated (id, condition) pairs")
    parser.add_argument("--conditions", nargs="+", default=None)
    args = parser.parse_args()

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("ERROR: GEMINI_API_KEY not set.", file=sys.stderr)
        sys.exit(1)
    client = genai.Client(api_key=api_key)

    if not os.path.exists(args.input):
        print(f"ERROR: {args.input} not found.", file=sys.stderr)
        sys.exit(1)

    results = load_results(args.input)

    if args.conditions:
        results = [r for r in results if r.get("condition") in args.conditions]

    if args.limit:
        grouped: dict = defaultdict(list)
        for r in results:
            grouped[r.get("condition", "unknown")].append(r)
        results = [r for group in grouped.values() for r in group[:args.limit]]

    # drop rows with no generated clarification 
    results = [r for r in results if r.get("generated_clarification")]

    completed = load_completed(args.output) if args.resume else set()
    to_eval = [r for r in results if (r["id"], r.get("condition")) not in completed]

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)

    with open(args.output, "a") as out_f:
        for r in tqdm(to_eval, desc="Judging"):
            scores = call_judge(
                client,
                ambiguous_question=r.get("ambiguous_question", ""),
                generated_clarification=r.get("generated_clarification", ""),
                gold_clarification=r.get("gold_clarification", ""),
                reasoning=r.get("reasoning"),
            )
            record = {
                "id": r["id"],
                "condition": r.get("condition"),
                "ambiguous_question": r.get("ambiguous_question", ""),
                "generated_clarification": r.get("generated_clarification", ""),
                "gold_clarification": r.get("gold_clarification", ""),
                "gold_intended_question": r.get("gold_intended_question", ""),
                **scores,
            }
            out_f.write(json.dumps(record) + "\n")
            out_f.flush()
            time.sleep(RETRY_DELAY)

    print_summary(args.output)


if __name__ == "__main__":
    main()